name: Asciidoctor Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Convert .adoc to HTML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7 # Adjust the version to match your project's Ruby version

      - name: Install Bundler
        run: gem install bundler

      - name: Install Asciidoctor using Bundler
        run: bundle install

      - name: Convert .adoc to HTML
        run: |
          mkdir -p html-files
          for f in *.adoc; do
            bundle exec asciidoctor -o "html-files/${f%.adoc}.html" "$f"
          done

      - name: Publish HTML artifacts
        uses: actions/upload-artifact@v2
        with:
          name: html-artifacts
          path: html-files
