name: Asciidoctor Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Convert .adoc to HTML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2 # Adjust the version to match your project's Ruby version

      - name: Install Asciidoctor
        run: gem install asciidoctor

      - name: Convert .adoc to HTML
        run: |
          for f in *.adoc; do
            asciidoctor -o "${f%.adoc}.html" "$f"
          done

      - name: Commit and push HTML files to the repository
        run: |
          git config user.name "AlphaCoder147"
          git config user.email "thescholar8101@gmail.com"
          git add *.html
          git commit -m "Update HTML files"
          git push origin main
